// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZCeQ7P7yodDinquUQiUq4pxnqd75uDsU',
    appId: '1:120301879243:web:9863bf575b10da78d3c04e',
    messagingSenderId: '120301879243',
    projectId: 'login-cf8a8',
    authDomain: 'login-cf8a8.firebaseapp.com',
    storageBucket: 'login-cf8a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDngCwJWpG2WH_GCMgGf-67-wqrBDv1TOU',
    appId: '1:120301879243:android:8e3c51f4c232723bd3c04e',
    messagingSenderId: '120301879243',
    projectId: 'login-cf8a8',
    storageBucket: 'login-cf8a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9pTc2Oq5lq01a4Os4_kFIkEsSC_FhjR8',
    appId: '1:120301879243:ios:d943c2b4b2a603c6d3c04e',
    messagingSenderId: '120301879243',
    projectId: 'login-cf8a8',
    storageBucket: 'login-cf8a8.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZCeQ7P7yodDinquUQiUq4pxnqd75uDsU',
    appId: '1:120301879243:web:06ba11a39ad86b25d3c04e',
    messagingSenderId: '120301879243',
    projectId: 'login-cf8a8',
    authDomain: 'login-cf8a8.firebaseapp.com',
    storageBucket: 'login-cf8a8.appspot.com',
  );
}
